### ISSUE TITLE
Passing double to kernel by value fails

### ISSUE THREAD

**Issue by jrprice** [hughperkins/coriander#22]
Passing a `double` value to a kernel by value like this:

    __global__ void foo(double* A, double x)
    {
      int  i = threadIdx.x;
      A[i] = x;
    }

Results in the following error when compiling with `cocl`:

    error: invalid forward reference to function 'setKernelArgFloat' with wrong type!
      call void @setKernelArgFloat(double %loadCudaArg1)
                ^
    1 error generated.

**Comment by hughperkins** [comment]
Ah, well spotted :-)

So, doubles are kind of a grey area. In theory, I dont support them at all, though I should probably state that somewhere. I do make some code that contains doubles at least compilable, though it will give the wrong results.

I dont currently have a rigorous statement of what is/isnt supported, though I probably should. In the case of doubles, its mostly not supported by design, though its not set in stone.

Why dont I support doubles? I'm mostly targeting getting machine learning libraries working, and they dont need doubles: floats, and fp16, work great in machine learning libraries. doubles are much slower on consumer-grade gpus, or any gpus really, and dont give obviously enhanced ml performance.

In your specific example, it's actually possible to make it compilable, and kind of working, by inserting the following into the start of the `PatchHostside::addSetKernelArgInst_float` function, in `patch_hostside.cpp`:

```
    Type *valueType = value->getType();
    cout << "addSetKernelArgInst_float, value type:" << endl;
    valueType->dump();
    cout << endl;
    if(valueType->isDoubleTy()) {
        cout << "is double" << endl;
        FPTruncInst *fpTrunc = new FPTruncInst(value, Type::getFloatTy(context), "trunctofloat");
        fpTrunc->insertAfter(lastInst);
        lastInst = fpTrunc;
        value = fpTrunc;
    }
```

However, this just delays the pain, since later on in your client code, you're going to have code like:
```
    cudaMemcpy(hostdoubles, gpudoubles, 4 * sizeof(double), cudaMemcpyDeviceToHost);
```
This will fail to give the right results, since the gpu was treating this buffer as an array of floats, and so the values are all in the wrong place, and have the wrong bit layout, if we then copy this into a hostside array of doubles.

So, I reckon it's better to just make the patchhostside fail for now. I'll do that now: 4802e5e

**Comment by hughperkins** [comment]
Started to document assumptions/relaxations here: https://github.com/hughperkins/coriander/blob/master/doc/assumptions.md
